version: '3'
services:
  db:
    image: postgres:9.5.3
    volumes:
      - ./sql:/app/sql
    ports:
      - "5432:5432"
    environment:
      - TERM=xterm
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=datica_users_dev

  shell:
    build: .
    command: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  package:
    image: datica-users:latest
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        binary: datica-users
    working_dir: /go/src/github.com/jcarley/datica-users
    volumes:
      - $PWD:/go/src/github.com/jcarley/datica-users
    depends_on:
      - db
